version: '3.8'

services:
  linguist-whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: linguist-whisper
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    restart: unless-stopped

  linguist-api:
    build: ./back
    image: kevynmurilo/linguist-api:latest
    container_name: linguist-api
    ports:
      - "${HOST_API_PORT}:8080"
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:${HOST_FRONT_PORT}
      - WHISPER_ENABLED=true
      - WHISPER_URL=http://linguist-whisper:9000
    depends_on:
      - linguist-whisper
    restart: unless-stopped

  linguist-front:
    build: ./front
    image: kevynmurilo/linguist-front:latest
    container_name: linguist-front
    ports:
      - "${HOST_FRONT_PORT}:80"
    depends_on:
      - linguist-api
    restart: unless-stopped

networks:
  default:
    name: linguist-network
