version: '3.8'

services:
  linguist-api:
    image: kevynmurilo/linguist-api:latest
    container_name: linguist-api
    ports:
      - "${HOST_API_PORT}:8080"
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:${HOST_FRONT_PORT}
    restart: unless-stopped

  linguist-front:
    image: kevynmurilo/linguist-front:latest
    container_name: linguist-front
    ports:
      - "${HOST_FRONT_PORT}:80"
    environment:
      - VITE_API_URL=http://localhost:${HOST_API_PORT}/api
    depends_on:
      - linguist-api
    restart: unless-stopped

networks:
  default:
    name: linguist-network